---
- name: get kops version # noqa 301
  command: "kops version | cut -d ' ' -f 2"
  register: kops_result
  ignore_errors: yes

- name: set kops current version fact
  set_fact:
      kops_current_version: "{{ kops_result.stdout|default('') }}"

- name: get latest stable kops tag
  uri:
    url: "{{ kops_release_api_url }}"
  ignore_errors: yes
  register: kops_github_result
  when: kops_version == 'latest'

- name: set kops version fact to latest
  set_fact:
       kops_version: "{{ kops_github_result.json.name|default(kops_default_version)|replace('v','') }}"
  when: kops_version == 'latest'

- name: set kops version fact to default
  set_fact:
    kops_version: "{{ kops_default_version }}"
  when: not kops_version

- name: "download kops binary {{ kops_version }}"
  get_url:
      url: "{{ kops_base_url }}/{{ kops_version }}/kops-linux-amd64"
      dest: /usr/local/bin/kops
      mode: 0755
      force: yes
  when: kops_current_version != kops_version
